"""add_user_uid_to_users

Revision ID: 17f820006cdf
Revises: bba2f4a04aec
Create Date: 2025-05-11 23:19:14.362881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f820006cdf'
down_revision: Union[str, None] = 'bba2f4a04aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uid', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_uid'), 'users', ['user_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_uid'), table_name='users')
    op.drop_column('users', 'user_uid')
    # ### end Alembic commands ###
