"""simplify_manufacturer_and_category_models

Revision ID: 53f0147ea8aa
Revises: f5e94e44f8a7
Create Date: 2025-05-12 01:43:10.800224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f0147ea8aa'
down_revision: Union[str, None] = 'f5e94e44f8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    op.add_column('manufacturers', sa.Column('country', sa.String(), nullable=True))
    op.drop_column('manufacturers', 'active')
    op.drop_column('manufacturers', 'phone')
    op.drop_column('manufacturers', 'logo_url')
    op.drop_column('manufacturers', 'email')
    op.drop_column('manufacturers', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('manufacturers', 'country')
    op.add_column('categories', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
