"""Add manufacturer_id to products

Revision ID: a8002dafccf3
Revises: 
Create Date: 2025-04-11 18:19:06.429877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8002dafccf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'manufacturers', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'manufacturer_id')
    # ### end Alembic commands ###
